apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: my-image
    volumeMounts:
    - name: my-volume
      mountPath: /my-directory
  volumes:
  - name: my-volume
    hostPath:
      path: /host/directory