apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  containers:
  - name: nfs-container
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(hostname) $(date) >> /mnt/data/out.txt; sleep 10; done"]
    volumeMounts:
    - name: nfs-volume
      mountPath: /mnt/data
  volumes:
  - name: nfs-volume
    nfs:
      server: <nfs-server-ip>
      path: /mnt/nfs_share