---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: secretv2
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-app
  name: secret-app
  namespace: secretv2
spec:
  restartPolicy: OnFailure
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    name: secret-app
    resources: {}
  dnsPolicy: ClusterFirst
status: {}
