apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod
  name: play-proto
spec:
  containers:
  - name: demo
    image: alpine
    command: ["sleep", "3600"]
    env:
      # define environment variable
        - name: APP-COLOR
          valueFrom:
            configMapKeyRef:
              name: play-proto
              key: app-env
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
