apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
spec:
  volumes:
  - name: logs
    emptyDir: {} # volume type. emptyDir will be installed on the host that is running the pods
  containers:
  - name: app
    image: busybox # represents the main application
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /var/log/date.txt; sleep 10; done"] # every 10 seconds, write the date to /var/log/date.txt
    volumeMounts:
    - name: logs
      mountPath: /var/log
  - name: sidecar # represents the web server
    image: centos/httpd
    ports:
    - containerPort: 80
    volumeMounts:
    - name: logs
      mountPath: /var/www/html # this has access to /var/log/date.txt


  # this is the usecase where aplication is generating data and outputting it to a file, 
  # and the webserver is used to present the data and make the data accesible. 